language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node --version
  - npm --version
  - npx --version
  - npm install -g codecov
before_script:
  - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.4.0
  - docker run -d --name node-chrome --link selenium-hub:hub selenium/node-chrome:3.4.0 --env CHROME_VERSION=latest
  - docker run -d --name node-firefox --link selenium-hub:hub selenium/node-firefox:3.4.0
script:
  - npm run e2e
  - codecov
after_script:
  - docker stop node-chrome
  - docker rm -v node-chrome
  - docker stop node-firefox
  - docker rm -v node-firefox
  - docker stop selenium-hub
  - docker rm -v selenium-hub
